### PR TITLE
initial post quantum identity key generation

### LINKED ISSUE #17: hash length is not user configurable
We should remove this option, hash length is not user configurable.

https://github.com/datapartyjs/dataparty-crypto/blob/13e0e17e0e38a1aa1afeab109c5de8e5a5b9b47c/src/routines.ts#L173

### LINKED ISSUE #21: BUG - update key type identifier
This should be checking for `nacl`

We probably have more test bugs, we should shake those out.

https://github.com/datapartyjs/dataparty-crypto/blob/5b363c929de0ffe5c570f083a4d06a4c6d90467b/test/message.spec.ts#L20

### LINKED ISSUE #23: FEAT |  Post quantum encryption support
## 🚀 Feature Proposal

Yeaah buddy, it's time to sprinkle some of that quantum resistant magic around. ✨🪄

 - [Google's Threat Model for Post Quantum Cryptography](https://bughunters.google.com/blog/5108747984306176/google-s-threat-model-for-post-quantum-cryptography)
 - OG node/js support [npm:crystals-kyber](https://github.com/antontutoveanu/crystals-kyber-javascript)
 - New TypeScript hotness [npm:crystals-kyber-js](https://github.com/dajiaji/crystals-kyber-js)

 - DiffieHelman using Nacl [npm:ed2curve-js](https://github.com/dchest/ed2curve-js)
   - https://github.com/paulmillr/noble-curves?tab=readme-ov-file#ed25519-x25519-ristretto255
 - HDKeys -  https://github.com/paulmillr/scure-bip32
 - Helpful AES and elliptic curve tools - https://github.com/paulmillr/noble-ciphers
 - Blog post explaining kyber selection process - https://blog.cr.yp.to/20231003-countcorrectly.html
 - https://crypto.stackexchange.com/questions/102671/is-aes-128-quantum-safe
 - `Quantum Security Analysis of AES` - https://eprint.iacr.org/2019/272.pdf
 - https://blog.cloudflare.com/nist-post-quantum-surprise/

 - https://crypto.stackexchange.com/questions/44386/are-cryptographic-hash-functions-quantum-secure
 - Strength of AES - https://crypto.stackexchange.com/questions/76738/has-aes-128-been-fully-broken

### LINKED ISSUE #25: Rework multi-key generation using hkdf
https://github.com/datapartyjs/dataparty-crypto/blob/fb0e62418457257ce416241e09e99d5d674e3b52/src/routines.ts#L93

https://crypto.stackexchange.com/questions/50582/how-does-hkdf-generate-2-keys

https://crypto.stackexchange.com/questions/20960/pbkdf-vs-hkdf-for-pretty-long-key

### PR DESCRIPTION
**Pull request by sevenbitbyte**
## Issues resolved:

- [x] closes #25 
- [x] closes #21
- [x] closes #17
- [x] closes #23 
  - [x] Nacl Shared Secret
  - [x] PQ Shared Secret
  - [x] Nacl Only AES Stream
  - [x] PQ Only AES Stream
  - [x] Nacl + PQ AES Stream

### CODE REVIEW

File: examples/pq-aes.js [hunk 1]
```diff
@@ -0,0 +1,119 @@
...
+    constructor(){
+        this.naclIdentity = new dataparty_crypto.Identity()
+        this.pqIdentity = new dataparty_crypto.PQIdentity()
+
+        this.naclSharedSecret = null
+        this.pqSharedSecret = null
+    }
+
+    async getStream(toIdentity){
+        this.naclSharedSecret = await dataparty_crypto.Routines.createNaclSharedSecret(
```
Comment (sevenbitbyte) [inline examples/pq-aes.js:20]: Library implementation of stream helpers should not store secrets after the stream is constructed.

**Comment by sevenbitbyte** [comment]
Cleanup entropy, seed and private key generation steps:

1. Mnemonic > entropy > pbkdf2( mnemonic(entropy), password ) > seed > hkdf(seed)
2. password > pbkdf2(password) > entropy > pbkdf2( mnemonic(entropy), blank_password ) > seed > hkdf(seed)
3. password > argon2(password) > entropy > pbkdf2( mnemonic(entropy), blank_password ) > seed > hkdf(seed)

File: src/routines.ts [hunk 2]
```diff
@@ -495,6 +597,67 @@ export const verifyData = async function(
   return sign.detached.verify(payloadHash, theirPayloadSignature, theirPublicSignKey)
 };
 
+export const createPQSharedSecret = async function(
+  to: IIdentity
+): Promise<IPQSharedSecret> {
+
+  const { cipherText, sharedSecret } = ml_kem768.encapsulate(base64.decode(to.key.public.box));
```
Comment (sevenbitbyte) [inline src/routines.ts:604]: Need to call the correct kyber variant based on the key type selected in the `to` field

File: src/routines.ts [hunk 3]
```diff
@@ -495,6 +597,67 @@ export const verifyData = async function(
...
+    sharedSecret: base64.encode(sharedSecret)
+  }
+};
+
+export const recoverPQSharedSecret = async function(
+  identity: IIdentity,    //! our identity
+  cipherText: string
+): Promise<IPQSharedSecret> {
+
+  const sharedSecret = ml_kem768.decapsulate(base64.decode(cipherText), base64.decode(identity.key.private.box));
```
Comment (sevenbitbyte) [inline src/routines.ts:634]: Use correct kyber variant

File: src/routines.ts [hunk 4]
```diff
@@ -495,6 +597,67 @@ export const verifyData = async function(
...
+
+export const createAESStream = async function(
+  naclSharedSecret: INaclSharedSecret,
+  pqSharedSecret: IPQSharedSecret,
+  salt: Uint8Array | string,
+  info: 	Uint8Array | string,
+  streamNonce: Uint8Array
+): Promise<IAESStream> {
+
+  const mergedSecret = Buffer.concat([
```
Comment (sevenbitbyte) [inline src/routines.ts:650]: Be flexible. Allow creating AES stream with one or both shared secret types

File: examples/pq-aes.js [hunk 5]
```diff
@@ -0,0 +1,116 @@
+let dataparty_crypto = require('../dist')
+
+
+const tweetnacl = require('tweetnacl')
+const hkdf = require('@panva/hkdf')
+const base64 = require('@stablelib/base64')
+
+const { siv } = require('@noble/ciphers/aes')
+
+class FullIdentity {
```
Comment (sevenbitbyte) [inline examples/pq-aes.js:10]: Update this example

File: src/routines.ts [hunk 6]
```diff
@@ -495,6 +597,67 @@ export const verifyData = async function(
...
+
+  const sharedSecret = ml_kem768.decapsulate(base64.decode(cipherText), base64.decode(identity.key.private.box));
+  
+  return {
+    cipherText, sharedSecret: base64.encode(sharedSecret)
+  }
+
+};
+
+export const createAESStream = async function(
```
Comment (sevenbitbyte) [inline src/routines.ts:642]: Support more than one AES strategy but default to `siv`
